import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'threads-test-'));
process.env.THREADS_DATA_DIR = dir;
try {
  const q = await import('../src/queue.js');
  const { inspectSession } = await import('../src/health.js');
  const file = path.join(dir, 'queue.json');
  fs.writeFileSync(file, JSON.stringify({ items: [{id:'old',status:'publishing',content:'old'}, {id:'legacy',status:'failed',content:'legacy'}] }));
  q.loadQueue();
  assert(q.getQueue().items.every(i => i.status === 'review'));
  assert.throws(() => q.retryItems('legacy'));
  q.clearFinished(); assert.equal(q.getQueue().items.length, 2);
  const a = q.addItem({content:'original', comments:['reply']});
  const b = q.addItem({content:'second'});
  assert.throws(() => q.addItem({content:'second'}));
  assert.throws(() => q.updateItem(a.id, {content:'second', comments:[]}));
  q.updateItem(a.id, {content:'edited',comments:['edited reply'],topic:'topic'});
  assert.equal(a.content,'edited');
  assert.throws(() => q.updateItem(a.id, {content:'x'.repeat(501),comments:[]}));
  assert.equal(a.content,'edited');
  q.moveItem(b.id,-1); assert(q.getQueue().items.indexOf(b)<q.getQueue().items.indexOf(a));
  await assert.rejects(q.publishItem(a.id, async () => {throw Error('before submit');}));
  assert.equal(a.status,'failed'); assert.equal(q.retryItems(a.id),1);
  await assert.rejects(q.publishItem(a.id, async ({onProgress}) => {
    await onProgress({stage:'submitting'});
    assert.equal(JSON.parse(fs.readFileSync(file)).items.find(i=>i.id===a.id).progress.stage,'submitting');
    await onProgress({stage:'posted',postUrl:'https://www.threads.com/@test/post/1',completedComments:[1]});
    throw Error('reply uncertain');
  }));
  assert.equal(a.status,'review'); assert.throws(()=>q.retryItems(a.id));
  assert.throws(()=>q.updateItem(a.id,{content:'duplicate',comments:[]}));
  assert.deepEqual(a.progress.completedComments,[1]);
  let release; const blocker = new Promise(r=>release=r);
  const pending = q.publishItem(b.id, async () => {await blocker; return {postUrl:'https://www.threads.com/@test/post/2'};});
  const c = q.addItem({content:'third'});
  await assert.rejects(q.publishItem(c.id, async()=>{throw Error('must not run');}), /다른 글/);
  release(); await pending; assert.equal(b.status,'done'); assert(b.postUrl);
  q.clearFinished(); assert(q.getQueue().items.includes(a)); assert(!q.getQueue().items.includes(b));
  assert.throws(()=>q.startQueue(Infinity)); assert.throws(()=>q.startQueue(1.5));
  q.startQueue(60); assert.throws(()=>q.updateItem(c.id,{content:'changed',comments:[]})); q.stopQueue();
  assert.equal(inspectSession(path.join(dir,'missing')).state,'missing');
  const session=path.join(dir,'session.json'); fs.writeFileSync(session, '{'); assert.equal(inspectSession(session).state,'invalid');
  fs.writeFileSync(session, JSON.stringify({cookies:[{expires:1}]})); assert.equal(inspectSession(session).state,'expired');
  fs.writeFileSync(session, JSON.stringify({cookies:[{expires:-1}]})); assert.equal(inspectSession(session).state,'unverified');
  console.log('PASS: crash recovery, partial failure lock, persisted progress, safe retry, edit validation, reordering, publish concurrency, schedule validation, session states');
} finally { fs.rmSync(dir,{recursive:true,force:true}); }
